In [1]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays

In [2]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])


In [3]:

print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [4]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [5]:
def predict_single_loop(x, w, b):
    
    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i] * w[i]
        p = p + p_i
    p = p + b
    return p

In [6]:
x = X_train[0]
p = predict_single_loop(x, w_init, b_init)
print(f"{p}, shape: {p.shape}")

459.9999976194083, shape: ()


In [7]:
x = X_train[1]
p = predict_single_loop(x, w_init, b_init)
print(f"{p}, shape: {p.shape}")

231.9999983694081, shape: ()


In [8]:
x = X_train[2]
p = predict_single_loop(x, w_init, b_init)
print(f"{p}, shape: {p.shape}")

177.99999898940814, shape: ()


In [9]:
def predict(x, w, b):
    
    p = np.dot(w, x) + b
    
    return p

In [10]:
p = predict(x, w_init, b_init)
print(f"{p}, shape:{p.shape}")

177.99999898940825, shape:()


Cost with multiple varaibles

In [11]:
def compute_cost(X, y, w, b):
    
    m = X.shape[0]
    j = 0
    
    for i in range(m):
        f_wb = np.dot(w, X[i]) + b
        j_i = (f_wb - y[i])**2
        j = j + j_i
    j = j / (2*m)
    return j

In [12]:
cost = compute_cost(X_train, y_train, w_init, b_init)
print(f"Cost at optimal w: {cost}")

Cost at optimal w: 1.5578904330213735e-12


In [53]:
def compute_gradient(X, y, w, b):
    
    m,n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.
   
    for i in range(m):
        error = (np.dot(X[i], w) + b) - y[i]
        
        for j in range(n):
            dj_dw[j] = dj_dw[j] + error * X[i,j]
        dj_db = dj_db + error
    dj_dw = dj_dw / m
    dj_db = dj_db /m
    return dj_db, dj_dw

In [54]:
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -1.6739251122999121e-06
dj_dw at initial w,b: 
 [-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05]


In [58]:
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters):
    
    J_history = []
    w = copy.deepcopy(w_in)  
    b = b_in
    
    for i in range(num_iters):

        dj_db,dj_dw = gradient_function(X, y, w, b)   

        w = w - alpha * dj_dw               
        b = b - alpha * dj_db               
    
        if i<100000:      
            J_history.append( cost_function(X, y, w, b))
            
        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")
        
    return w, b, J_history 

In [59]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.

iterations = 10000
alpha = 5.0e-7


w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient, 
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

Iteration    0: Cost  2529.46   
Iteration 1000: Cost   686.69   
Iteration 2000: Cost   677.19   
Iteration 3000: Cost   668.48   
Iteration 4000: Cost   660.50   
Iteration 5000: Cost   653.19   
Iteration 6000: Cost   646.49   
Iteration 7000: Cost   640.35   
Iteration 8000: Cost   634.72   
Iteration 9000: Cost   629.56   
b,w found by gradient descent: -0.02,[ 0.22  0.03 -0.11 -0.58] 
prediction: 430.50, target value: 460
prediction: 283.93, target value: 232
prediction: 164.52, target value: 178
